spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: #your mysql username
    password: #your mysql password
  jpa:
    hibernate:
      ddl-auto: create

#JPA Settings
